#!/usr/bin/env python3
"""Run constrained PA synthesis with the 2026-05-04 simplified TF model.

This script is a focused experiment rather than a replacement for
``run_pa_synthesis_pipeline.py``:
  - transformer S4P is generated by ``Cal_0504.py`` in automatic W/R mode;
  - six-port TF assembly uses ``TF_Cal_S6P_Predicting_0504.py``;
  - full PA is built with the existing scikit-rf cascade convention;
  - candidates that satisfy 35-75 GHz S21 constraints are ranked by OMN
    input impedance error against loadpull Zopt(f).
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
import time
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import skrf as rf

import Cal_0504
import TF_Cal_S6P_Predicting_0504 as tf0504
from bilinear_L_predictor import predict_l_params
from VCL_length_calculator import calculate_compensation_msl
from pa_synthesis.config import PaSynthesisConfig, inclusive_float_range
from pa_synthesis.data_loaders import load_loadpull_zopt, load_transistor_s4p, make_frequency
from pa_synthesis.network_utils import (
    align_network,
    s21_db,
    transformer_omn_input_impedances,
)
from pa_synthesis.objectives import omn_impedance_loss


BASE = Path(__file__).resolve().parent
OUT_DIR = BASE / "outputs" / "pa_synthesis_pipeline" / "pa_synthesis_0504_constrained_rank"
FIG_DIR = OUT_DIR / "figures"
CACHE_DIR = OUT_DIR / "cache"
S4P_DIR = CACHE_DIR / "cal0504_s4p_30_80_1GHz_autoWR"
S6P_DIR = CACHE_DIR / "tf6_0504"

FREQ_GHZ = np.arange(30.0, 80.0 + 1e-9, 1.0)
FREQ_HZ = FREQ_GHZ * 1e9
TARGET_FREQ = make_frequency(FREQ_HZ)
REFERENCE = {
    "IMN": {"W_um": 114.0, "R": 1.60},
    "ISMN": {"W_um": 106.0, "R": 1.30},
    "OMN": {"W_um": 104.0, "R": 1.68},
}


def safe_tag(value: float, digits: int = 5) -> str:
    text = f"{float(value):.{digits}f}".rstrip("0").rstrip(".")
    return text.replace("-", "m").replace(".", "p")


def wr_key(w_um: float, r: float) -> tuple[float, float]:
    return round(float(w_um), 6), round(float(r), 6)


def candidate_grids() -> tuple[list[tuple[float, float]], list[tuple[float, float]], list[tuple[float, float]]]:
    imn = [
        (w, r)
        for w in inclusive_float_range(108.0, 114.0, 1.0)
        for r in [1.35, 1.40, 1.45, 1.50, 1.55, 1.60]
    ]
    ismn = [
        (w, r)
        for w in inclusive_float_range(104.0, 107.0, 0.5)
        for r in [1.20, 1.22, 1.24, 1.26, 1.28, 1.30]
    ]
    omn = [
        (w, r)
        for w in inclusive_float_range(100.0, 104.0, 0.5)
        for r in [1.60, 1.62, 1.64, 1.66, 1.68, 1.70, 1.72, 1.74, 1.75]
    ]
    for role, grid in [
        ("IMN", imn),
        ("ISMN", ismn),
        ("OMN", omn),
    ]:
        ref = wr_key(REFERENCE[role]["W_um"], REFERENCE[role]["R"])
        if ref not in {wr_key(w, r) for w, r in grid}:
            grid.append(ref)
    return imn, ismn, omn


class Transformer0504Predictor:
    def __init__(self) -> None:
        self.cache: dict[tuple[float, float], rf.Network] = {}
        S4P_DIR.mkdir(parents=True, exist_ok=True)
        S6P_DIR.mkdir(parents=True, exist_ok=True)

    def s4p_path_for(self, w_um: float, r: float) -> Path:
        return S4P_DIR / Cal_0504.default_filename(w_um, r, Cal_0504.DEFAULT_LENGTH_SCALE, Cal_0504.DEFAULT_SLOT_RATIO)

    def build(self, w_um: float, r: float, *, name: str) -> rf.Network:
        key = wr_key(w_um, r)
        if key in self.cache:
            out = self.cache[key].copy()
            out.name = name
            return out

        s4p_path = Cal_0504.generate_s4p(
            w_um=float(w_um),
            r=float(r),
            output_dir=S4P_DIR,
            # Important: use automatic W/R geometry here, not Cal_0504's
            # manual ADS-probing defaults.
            w_line_um=None,
            line_length_um=None,
            length_scale=Cal_0504.DEFAULT_LENGTH_SCALE,
            slot_ratio=Cal_0504.DEFAULT_SLOT_RATIO,
            freq_start_ghz=float(FREQ_GHZ[0]),
            freq_stop_ghz=float(FREQ_GHZ[-1]),
            freq_step_ghz=float(FREQ_GHZ[1] - FREQ_GHZ[0]),
            quiet=True,
            write_manifest=True,
        )
        inductors = predict_l_params(float(w_um), float(r))
        local_cfg = dict(tf0504.CFG)
        local_cfg.update(
            {
                "s4p_top": str(s4p_path),
                "s4p_bot": str(s4p_path),
                "f_start_ghz": float(FREQ_GHZ[0]),
                "f_stop_ghz": float(FREQ_GHZ[-1]),
                "f_step_ghz": float(FREQ_GHZ[1] - FREQ_GHZ[0]),
                "z0": 50.0,
                "L13_nH": float(inductors["L13_nH"]),
                "L24_nH": float(inductors["L24_nH"]),
                "L56_pH": float(inductors["L56_pH"]),
                "L56V_extra_pH": 0.0,
                "out_dir": str(S6P_DIR),
                "out_name": f"tf6_0504_W{safe_tag(w_um)}_R{safe_tag(r)}",
            }
        )
        ntw = tf0504.build_tf_6port(local_cfg)
        ntw = align_network(ntw, FREQ_HZ, name=f"tf6_0504_W{safe_tag(w_um)}_R{safe_tag(r)}")
        self.cache[key] = ntw.copy()
        out = ntw.copy()
        out.name = name
        return out

    def describe(self, w_um: float, r: float) -> dict[str, Any]:
        geom = calculate_compensation_msl(float(w_um), float(r))
        inductors = predict_l_params(float(w_um), float(r))
        return {
            "W_um": float(w_um),
            "R": float(r),
            "cal0504_s4p": str(self.s4p_path_for(w_um, r)),
            "geometry": geom,
            "inductors": inductors,
            "length_scale": Cal_0504.DEFAULT_LENGTH_SCALE,
            "slot_ratio": Cal_0504.DEFAULT_SLOT_RATIO,
            "model_note": "no compensation MLIN, no L56delta; Cal_0504 S4P generated in auto-W/R mode",
        }


def gain_metrics(ntw: rf.Network) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    gain = s21_db(ntw)
    s11 = 20.0 * np.log10(np.maximum(np.abs(ntw.s[:, 0, 0]), 1e-30))
    mask_35_75 = (FREQ_GHZ >= 35.0) & (FREQ_GHZ <= 75.0)
    gw = gain[mask_35_75]
    peak_30_80 = float(np.max(gain))
    threshold = peak_30_80 - 3.0
    min_35_75 = float(np.min(gw))
    max_35_75 = float(np.max(gw))
    min_30_80 = float(np.min(gain))
    max_30_80 = float(np.max(gain))
    metrics = {
        "s21_min_35_75_db": min_35_75,
        "s21_max_35_75_db": max_35_75,
        "s21_mean_35_75_db": float(np.mean(gw)),
        "s21_ripple_35_75_db": float(max_35_75 - min_35_75),
        "s21_peak_30_80_db": peak_30_80,
        "s21_min_30_80_db": min_30_80,
        "s21_max_30_80_db": max_30_80,
        "s21_ripple_30_80_db": float(max_30_80 - min_30_80),
        "threshold_3db_from_peak_30_80_db": threshold,
        "max_3db_deficit_35_75_db": float(max(threshold - min_35_75, 0.0)),
        "max_low_gain_violation_35_75_db": float(max(16.0 - min_35_75, 0.0)),
        "max_high_gain_violation_35_75_db": float(max(max_35_75 - 20.5, 0.0)),
        "strict_pass_35_75": bool(min_35_75 >= 16.0 and max_35_75 <= 20.5 and min_35_75 >= threshold),
        "ideal_pass_30_80": bool(min_30_80 >= 16.0 and max_30_80 <= 20.5 and min_30_80 >= threshold),
        "s11_min_30_80_db": float(np.min(s11)),
        "s11_max_30_80_db": float(np.max(s11)),
    }
    return gain, s11, metrics


def s_from_y_2port(y2: np.ndarray, z0: float = 50.0) -> np.ndarray:
    """Convert a stack of 2-port admittance matrices to S parameters."""
    eye = np.eye(2, dtype=complex)[None, :, :]
    return (eye - z0 * y2) @ np.linalg.inv(eye + z0 * y2)


def add_network_y(
    y_global: np.ndarray,
    y_local: np.ndarray,
    port_to_node: list[int | None],
) -> None:
    """Stamp a multiport Y matrix into the fixed PA nodal admittance matrix.

    ``None`` means that the corresponding circuit port is tied to ideal ground.
    Open ports are represented as ordinary internal nodes and later eliminated.
    """
    for local_i, node_i in enumerate(port_to_node):
        if node_i is None:
            continue
        for local_j, node_j in enumerate(port_to_node):
            if node_j is None:
                continue
            y_global[:, node_i, node_j] += y_local[:, local_i, local_j]


def build_full_pa_y_fast(
    *,
    driver_s4p: rf.Network,
    final_s4p: rf.Network,
    imn: rf.Network,
    ismn: rf.Network,
    omn: rf.Network,
) -> np.ndarray:
    """Return the exact 2-port PA Y matrix for the agreed fixed connections.

    This is algebraically equivalent to ``build_full_pa_network`` with
    ``include_dc_blocks=False`` for the 0504 synthesis topology, but avoids
    constructing a scikit-rf ``Circuit`` for every grid point.

    Node convention:
      0 PA input, 1 PA output,
      2/3 driver input pair, 4/5 driver output pair,
      6/7 final input pair, 8/9 final output pair,
      10/11/12 open MATAP nodes for IMN/ISMN/OMN.
    """
    nfreq = len(driver_s4p.f)
    y_global = np.zeros((nfreq, 13, 13), dtype=complex)

    add_network_y(y_global, imn.y, [2, 3, 0, None, None, 10])
    add_network_y(y_global, driver_s4p.y, [2, 3, 4, 5])
    add_network_y(y_global, ismn.y, [4, 5, 6, 7, None, 11])
    add_network_y(y_global, final_s4p.y, [6, 7, 8, 9])
    add_network_y(y_global, omn.y, [8, 9, 1, None, None, 12])

    keep = [0, 1]
    internal = list(range(2, 13))
    y_reduced = np.zeros((nfreq, 2, 2), dtype=complex)
    for idx in range(nfreq):
        ykk = y_global[idx][np.ix_(keep, keep)]
        yki = y_global[idx][np.ix_(keep, internal)]
        yik = y_global[idx][np.ix_(internal, keep)]
        yii = y_global[idx][np.ix_(internal, internal)]
        y_reduced[idx] = ykk - yki @ np.linalg.solve(yii, yik)
    return y_reduced


def gain_metrics_from_y(y2: np.ndarray, *, z0: float = 50.0) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    s2 = s_from_y_2port(y2, z0=z0)
    gain = 20.0 * np.log10(np.maximum(np.abs(s2[:, 1, 0]), 1e-30))
    s11 = 20.0 * np.log10(np.maximum(np.abs(s2[:, 0, 0]), 1e-30))
    mask_35_75 = (FREQ_GHZ >= 35.0) & (FREQ_GHZ <= 75.0)
    gw = gain[mask_35_75]
    peak_30_80 = float(np.max(gain))
    threshold = peak_30_80 - 3.0
    min_35_75 = float(np.min(gw))
    max_35_75 = float(np.max(gw))
    min_30_80 = float(np.min(gain))
    max_30_80 = float(np.max(gain))
    metrics = {
        "s21_min_35_75_db": min_35_75,
        "s21_max_35_75_db": max_35_75,
        "s21_mean_35_75_db": float(np.mean(gw)),
        "s21_ripple_35_75_db": float(max_35_75 - min_35_75),
        "s21_peak_30_80_db": peak_30_80,
        "s21_min_30_80_db": min_30_80,
        "s21_max_30_80_db": max_30_80,
        "s21_ripple_30_80_db": float(max_30_80 - min_30_80),
        "threshold_3db_from_peak_30_80_db": threshold,
        "max_3db_deficit_35_75_db": float(max(threshold - min_35_75, 0.0)),
        "max_low_gain_violation_35_75_db": float(max(16.0 - min_35_75, 0.0)),
        "max_high_gain_violation_35_75_db": float(max(max_35_75 - 20.5, 0.0)),
        "strict_pass_35_75": bool(min_35_75 >= 16.0 and max_35_75 <= 20.5 and min_35_75 >= threshold),
        "ideal_pass_30_80": bool(min_30_80 >= 16.0 and max_30_80 <= 20.5 and min_30_80 >= threshold),
        "s11_min_30_80_db": float(np.min(s11)),
        "s11_max_30_80_db": float(np.max(s11)),
    }
    return gain, s11, metrics


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    for row in rows:
        for key, value in row.items():
            if key not in fields and not isinstance(value, (dict, list)):
                fields.append(key)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def rank_rows(rows: list[dict[str, Any]], prefix: str) -> list[dict[str, Any]]:
    out = sorted(
        rows,
        key=lambda row: (
            row["omn_z_loss"],
            row["s21_ripple_35_75_db"],
            abs(row["s21_mean_35_75_db"] - 18.0),
            row["W_IMN_um"],
            row["R_IMN"],
            row["W_ISMN_um"],
            row["R_ISMN"],
            row["W_OMN_um"],
            row["R_OMN"],
        ),
    )
    lower_by_loss = {}
    losses = sorted({round(row["omn_z_loss"], 15) for row in out})
    for loss in losses:
        lower_by_loss[loss] = 1 + sum(1 for row in out if round(row["omn_z_loss"], 15) < loss)
    for idx, row in enumerate(out, start=1):
        row[f"{prefix}_row_rank"] = idx
        row[f"{prefix}_competition_rank_by_omn_z"] = lower_by_loss[round(row["omn_z_loss"], 15)]
    return out


def unique_omn_rank(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_omn: dict[tuple[float, float], dict[str, Any]] = {}
    for row in rows:
        key = wr_key(row["W_OMN_um"], row["R_OMN"])
        by_omn.setdefault(
            key,
            {
                "W_OMN_um": row["W_OMN_um"],
                "R_OMN": row["R_OMN"],
                "omn_z_loss": row["omn_z_loss"],
                "omn_mean_abs_z_error_ohm": row["omn_mean_abs_z_error_ohm"],
                "omn_max_abs_z_error_ohm": row["omn_max_abs_z_error_ohm"],
                "qualified_combo_count_with_this_omn": 0,
            },
        )
        by_omn[key]["qualified_combo_count_with_this_omn"] += 1
    vals = sorted(by_omn.values(), key=lambda row: (row["omn_z_loss"], row["W_OMN_um"], row["R_OMN"]))
    for idx, row in enumerate(vals, start=1):
        row["unique_omn_rank"] = idx
    return vals


def plot_responses(reference_response: dict[str, Any], best_response: dict[str, Any], path: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(8.5, 6.0), dpi=160, sharex=True)
    axes[0].plot(FREQ_GHZ, reference_response["s21_db"], linewidth=2.0, label="Reference group S21")
    axes[0].plot(FREQ_GHZ, best_response["s21_db"], linewidth=2.0, linestyle="--", label="Top ranked qualified S21")
    axes[0].axhspan(16.0, 20.5, color="#b3de69", alpha=0.18, label="16-20.5 dB")
    axes[0].axvspan(35.0, 75.0, color="#80b1d3", alpha=0.15, label="35-75 GHz")
    axes[0].set_ylabel("S21 (dB)")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(loc="best")

    axes[1].plot(FREQ_GHZ, reference_response["s11_db"], linewidth=2.0, label="Reference group S11")
    axes[1].plot(FREQ_GHZ, best_response["s11_db"], linewidth=2.0, linestyle="--", label="Top ranked qualified S11")
    axes[1].axvspan(35.0, 75.0, color="#80b1d3", alpha=0.15)
    axes[1].set_xlabel("Frequency (GHz)")
    axes[1].set_ylabel("S11 (dB)")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(loc="best")
    fig.suptitle("PA 0504 Model: Reference vs Top OMN-Z Ranked Qualified Candidate")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_omn_z(loadpull, omn_scores: dict[tuple[float, float], dict[str, Any]], cases: list[tuple[str, float, float]], path: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(8.5, 6.0), dpi=160, sharex=True)
    f = loadpull.freq_ghz
    axes[0].plot(f, loadpull.zopt_single.real, "o-", linewidth=1.8, label="Loadpull Zopt Re")
    axes[1].plot(f, loadpull.zopt_single.imag, "o-", linewidth=1.8, label="Loadpull Zopt Im")
    for label, w, r in cases:
        score = omn_scores[wr_key(w, r)]
        axes[0].plot(f, score["zavg_re_ohm"], "s--", linewidth=1.4, label=f"{label} Re W{w:g} R{r:g}")
        axes[1].plot(f, score["zavg_im_ohm"], "s--", linewidth=1.4, label=f"{label} Im W{w:g} R{r:g}")
    axes[0].set_ylabel("Resistance (ohm)")
    axes[1].set_ylabel("Reactance (ohm)")
    axes[1].set_xlabel("Frequency (GHz)")
    for ax in axes:
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best")
    fig.suptitle("OMN Zin vs Loadpull Zopt After PA Qualification")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def main() -> int:
    t0 = time.perf_counter()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    cfg = PaSynthesisConfig()
    loadpull = load_loadpull_zopt(cfg.paths.loadpull_excel, f_start_ghz=30.0, f_stop_ghz=80.0)
    loadpull_indices = [int(np.argmin(np.abs(FREQ_GHZ - fghz))) for fghz in loadpull.freq_ghz]

    driver = load_transistor_s4p(cfg.paths.driver_transistor_s4p, target_freq_hz=FREQ_HZ, z0=50.0, name="driver_2x12")
    final = load_transistor_s4p(cfg.paths.final_transistor_s4p, target_freq_hz=FREQ_HZ, z0=50.0, name="final_2x18")
    predictor = Transformer0504Predictor()

    imn_grid, ismn_grid, omn_grid = candidate_grids()
    all_wr = sorted({wr_key(w, r) for w, r in imn_grid + ismn_grid + omn_grid})
    tf_cache: dict[tuple[float, float], rf.Network] = {}
    for idx, (w, r) in enumerate(all_wr, start=1):
        tf_cache[(w, r)] = predictor.build(w, r, name=f"tf6_0504_W{w:g}_R{r:g}")
        if idx % 25 == 0:
            print(f"[build] {idx}/{len(all_wr)} transformer networks")

    omn_scores: dict[tuple[float, float], dict[str, Any]] = {}
    for w, r in omn_grid:
        key = wr_key(w, r)
        z1, z2, zavg_full = transformer_omn_input_impedances(tf_cache[key], load_ohm=50.0)
        zavg = zavg_full[loadpull_indices]
        err = zavg - loadpull.zopt_single
        loss = omn_impedance_loss(zavg, loadpull.zopt_single, cfg.objectives)
        omn_scores[key] = {
            "omn_z_loss": float(loss.loss),
            "omn_mean_abs_z_error_ohm": float(np.mean(np.abs(err))),
            "omn_median_abs_z_error_ohm": float(np.median(np.abs(err))),
            "omn_rms_abs_z_error_ohm": float(np.sqrt(np.mean(np.abs(err) ** 2))),
            "omn_max_abs_z_error_ohm": float(np.max(np.abs(err))),
            "omn_mean_real_error_ohm": float(np.mean(err.real)),
            "omn_mean_imag_error_ohm": float(np.mean(err.imag)),
            "zavg_re_ohm": zavg.real.tolist(),
            "zavg_im_ohm": zavg.imag.tolist(),
        }

    rows: list[dict[str, Any]] = []
    response_by_key: dict[tuple[float, float, float, float, float, float], dict[str, Any]] = {}
    total = len(imn_grid) * len(ismn_grid) * len(omn_grid)
    evaluated = 0
    last_print = time.perf_counter()
    for w_imn, r_imn in imn_grid:
        for w_ismn, r_ismn in ismn_grid:
            for w_omn, r_omn in omn_grid:
                combo_key = (w_imn, r_imn, w_ismn, r_ismn, w_omn, r_omn)
                try:
                    y2 = build_full_pa_y_fast(
                        driver_s4p=driver,
                        final_s4p=final,
                        imn=tf_cache[wr_key(w_imn, r_imn)],
                        ismn=tf_cache[wr_key(w_ismn, r_ismn)],
                        omn=tf_cache[wr_key(w_omn, r_omn)],
                    )
                    gain, s11, metrics = gain_metrics_from_y(y2, z0=50.0)
                    row = {
                        "status": "ok",
                        "W_IMN_um": float(w_imn),
                        "R_IMN": float(r_imn),
                        "W_ISMN_um": float(w_ismn),
                        "R_ISMN": float(r_ismn),
                        "W_OMN_um": float(w_omn),
                        "R_OMN": float(r_omn),
                        **metrics,
                        **{k: v for k, v in omn_scores[wr_key(w_omn, r_omn)].items() if not isinstance(v, list)},
                        "is_reference_group": bool(
                            wr_key(w_imn, r_imn) == wr_key(REFERENCE["IMN"]["W_um"], REFERENCE["IMN"]["R"])
                            and wr_key(w_ismn, r_ismn) == wr_key(REFERENCE["ISMN"]["W_um"], REFERENCE["ISMN"]["R"])
                            and wr_key(w_omn, r_omn) == wr_key(REFERENCE["OMN"]["W_um"], REFERENCE["OMN"]["R"])
                        ),
                    }
                    rows.append(row)
                    if row["is_reference_group"]:
                        response_by_key[combo_key] = {"s21_db": gain.tolist(), "s11_db": s11.tolist()}
                except Exception as exc:
                    rows.append(
                        {
                            "status": "error",
                            "error": str(exc),
                            "W_IMN_um": float(w_imn),
                            "R_IMN": float(r_imn),
                            "W_ISMN_um": float(w_ismn),
                            "R_ISMN": float(r_ismn),
                            "W_OMN_um": float(w_omn),
                            "R_OMN": float(r_omn),
                        }
                    )
                evaluated += 1
                if evaluated % 1000 == 0 or time.perf_counter() - last_print > 60.0:
                    print(f"[eval] {evaluated}/{total} full PA candidates")
                    last_print = time.perf_counter()

    ok_rows = [row for row in rows if row.get("status") == "ok"]
    strict_rows = [row for row in ok_rows if row["strict_pass_35_75"]]
    ideal_rows = [row for row in ok_rows if row["ideal_pass_30_80"]]
    strict_ranked = rank_rows(strict_rows, "strict35_75")
    ideal_ranked = rank_rows(ideal_rows, "ideal30_80")
    strict_unique_omn = unique_omn_rank(strict_rows)
    ideal_unique_omn = unique_omn_rank(ideal_rows)

    reference_row = next((row for row in ok_rows if row.get("is_reference_group")), None)
    reference_strict = next((row for row in strict_ranked if row.get("is_reference_group")), None)
    reference_ideal = next((row for row in ideal_ranked if row.get("is_reference_group")), None)
    reference_omn_strict = next(
        (row for row in strict_unique_omn if wr_key(row["W_OMN_um"], row["R_OMN"]) == wr_key(104.0, 1.68)),
        None,
    )
    reference_omn_ideal = next(
        (row for row in ideal_unique_omn if wr_key(row["W_OMN_um"], row["R_OMN"]) == wr_key(104.0, 1.68)),
        None,
    )

    write_csv(OUT_DIR / "all_candidate_s21_and_omn_z_metrics.csv", ok_rows)
    write_csv(OUT_DIR / "qualified_strict35_75_omn_z_rank.csv", strict_ranked)
    write_csv(OUT_DIR / "qualified_strict35_75_omn_z_rank_top100.csv", strict_ranked[:100])
    write_csv(OUT_DIR / "qualified_ideal30_80_omn_z_rank.csv", ideal_ranked)
    write_csv(OUT_DIR / "qualified_ideal30_80_omn_z_rank_top100.csv", ideal_ranked[:100])
    write_csv(OUT_DIR / "qualified_strict35_75_unique_omn_rank.csv", strict_unique_omn)
    write_csv(OUT_DIR / "qualified_ideal30_80_unique_omn_rank.csv", ideal_unique_omn)

    best_strict = strict_ranked[0] if strict_ranked else None
    if best_strict and reference_row:
        best_key = (
            best_strict["W_IMN_um"],
            best_strict["R_IMN"],
            best_strict["W_ISMN_um"],
            best_strict["R_ISMN"],
            best_strict["W_OMN_um"],
            best_strict["R_OMN"],
        )
        if best_key not in response_by_key:
            y2_best = build_full_pa_y_fast(
                driver_s4p=driver,
                final_s4p=final,
                imn=tf_cache[wr_key(best_strict["W_IMN_um"], best_strict["R_IMN"])],
                ismn=tf_cache[wr_key(best_strict["W_ISMN_um"], best_strict["R_ISMN"])],
                omn=tf_cache[wr_key(best_strict["W_OMN_um"], best_strict["R_OMN"])],
            )
            g, s, _ = gain_metrics_from_y(y2_best, z0=50.0)
            response_by_key[best_key] = {"s21_db": g.tolist(), "s11_db": s.tolist()}
        ref_key = (
            REFERENCE["IMN"]["W_um"],
            REFERENCE["IMN"]["R"],
            REFERENCE["ISMN"]["W_um"],
            REFERENCE["ISMN"]["R"],
            REFERENCE["OMN"]["W_um"],
            REFERENCE["OMN"]["R"],
        )
        plot_responses(
            response_by_key[ref_key],
            response_by_key[best_key],
            FIG_DIR / "reference_vs_top_ranked_s21_s11.png",
        )
        plot_omn_z(
            loadpull,
            omn_scores,
            [
                ("Reference", REFERENCE["OMN"]["W_um"], REFERENCE["OMN"]["R"]),
                ("Top strict", best_strict["W_OMN_um"], best_strict["R_OMN"]),
            ],
            FIG_DIR / "reference_and_top_ranked_omn_zin_vs_zopt.png",
        )

    with (OUT_DIR / "reference_group_response_s11_s21_30_80.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["freq_ghz", "s21_db", "s11_db"])
        ref_key = (
            REFERENCE["IMN"]["W_um"],
            REFERENCE["IMN"]["R"],
            REFERENCE["ISMN"]["W_um"],
            REFERENCE["ISMN"]["R"],
            REFERENCE["OMN"]["W_um"],
            REFERENCE["OMN"]["R"],
        )
        ref_response = response_by_key.get(ref_key)
        if ref_response:
            for fghz, gain, s11 in zip(FREQ_GHZ, ref_response["s21_db"], ref_response["s11_db"]):
                writer.writerow([float(fghz), float(gain), float(s11)])

    summary = {
        "model": {
            "s4p_generator": "Cal_0504.py in auto-W/R mode",
            "tf6_builder": "TF_Cal_S6P_Predicting_0504.py",
            "length_scale": Cal_0504.DEFAULT_LENGTH_SCALE,
            "slot_ratio": Cal_0504.DEFAULT_SLOT_RATIO,
            "no_compensation_mlines": True,
            "no_l56delta": True,
            "include_dc_blocks": False,
        },
        "frequency_grid_ghz": [float(FREQ_GHZ[0]), float(FREQ_GHZ[-1]), float(FREQ_GHZ[1] - FREQ_GHZ[0])],
        "constraints": {
            "strict35_75": "35-75 GHz all S21 in 16-20.5 dB and within 3 dB of peak over 30-80 GHz",
            "ideal30_80": "30-80 GHz all S21 in 16-20.5 dB and within 3 dB of peak over 30-80 GHz",
        },
        "grid_counts": {
            "IMN": len(imn_grid),
            "ISMN": len(ismn_grid),
            "OMN": len(omn_grid),
            "total_combinations": total,
            "unique_transformer_networks": len(all_wr),
        },
        "num_ok": len(ok_rows),
        "num_strict35_75_pass": len(strict_rows),
        "num_ideal30_80_pass": len(ideal_rows),
        "reference_dimensions": REFERENCE,
        "reference_metrics": reference_row,
        "reference_in_strict35_75": reference_strict is not None,
        "reference_strict35_75_rank": reference_strict,
        "reference_strict35_75_unique_omn_rank": reference_omn_strict,
        "reference_in_ideal30_80": reference_ideal is not None,
        "reference_ideal30_80_rank": reference_ideal,
        "reference_ideal30_80_unique_omn_rank": reference_omn_ideal,
        "best_strict35_75": best_strict,
        "best_ideal30_80": ideal_ranked[0] if ideal_ranked else None,
        "top10_strict35_75": strict_ranked[:10],
        "top10_ideal30_80": ideal_ranked[:10],
        "compensation_parameters": {
            "IMN": predictor.describe(REFERENCE["IMN"]["W_um"], REFERENCE["IMN"]["R"]),
            "ISMN": predictor.describe(REFERENCE["ISMN"]["W_um"], REFERENCE["ISMN"]["R"]),
            "OMN": predictor.describe(REFERENCE["OMN"]["W_um"], REFERENCE["OMN"]["R"]),
        },
        "elapsed_seconds": time.perf_counter() - t0,
        "outputs": {
            "out_dir": str(OUT_DIR),
            "strict_rank_csv": str(OUT_DIR / "qualified_strict35_75_omn_z_rank.csv"),
            "strict_top100_csv": str(OUT_DIR / "qualified_strict35_75_omn_z_rank_top100.csv"),
            "strict_unique_omn_csv": str(OUT_DIR / "qualified_strict35_75_unique_omn_rank.csv"),
            "ideal_rank_csv": str(OUT_DIR / "qualified_ideal30_80_omn_z_rank.csv"),
            "fig_response": str(FIG_DIR / "reference_vs_top_ranked_s21_s11.png"),
            "fig_omn_z": str(FIG_DIR / "reference_and_top_ranked_omn_zin_vs_zopt.png"),
        },
    }
    with (OUT_DIR / "pa_synthesis_0504_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)

    print(
        json.dumps(
            {
                "num_ok": len(ok_rows),
                "num_strict35_75_pass": len(strict_rows),
                "num_ideal30_80_pass": len(ideal_rows),
                "reference_in_strict35_75": reference_strict is not None,
                "reference_strict35_75_rank": None
                if reference_strict is None
                else {
                    "row_rank": reference_strict.get("strict35_75_row_rank"),
                    "competition_rank_by_omn_z": reference_strict.get("strict35_75_competition_rank_by_omn_z"),
                    "omn_z_loss": reference_strict.get("omn_z_loss"),
                    "omn_mean_abs_z_error_ohm": reference_strict.get("omn_mean_abs_z_error_ohm"),
                    "s21_min_35_75_db": reference_strict.get("s21_min_35_75_db"),
                    "s21_max_35_75_db": reference_strict.get("s21_max_35_75_db"),
                    "s21_ripple_35_75_db": reference_strict.get("s21_ripple_35_75_db"),
                },
                "reference_unique_omn_rank": reference_omn_strict,
                "best_strict35_75": None
                if best_strict is None
                else {
                    key: best_strict[key]
                    for key in [
                        "W_IMN_um",
                        "R_IMN",
                        "W_ISMN_um",
                        "R_ISMN",
                        "W_OMN_um",
                        "R_OMN",
                        "omn_z_loss",
                        "omn_mean_abs_z_error_ohm",
                        "s21_min_35_75_db",
                        "s21_max_35_75_db",
                        "s21_ripple_35_75_db",
                    ]
                },
                "elapsed_seconds": summary["elapsed_seconds"],
                "out_dir": str(OUT_DIR),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
