#!/usr/bin/env python3
"""Six-port transformer assembly for the 2026-05-04 simplified model.

This module is only the six-port assembler. It consumes already existing
four-port S4P files through cfg["s4p_top"] and cfg["s4p_bot"]; it does not
care whether those S4P files were generated by Cal_0504/SG-DVCL, exported
from HFSS/EM, or produced by another equivalent model.

Compared with ``TF_Cal_S6P_Predicting.py``:
  - no compensation microstrip lines on the E1TAP/MATAP branches;
  - no L56delta, so the outer series inductors use L56 only;
  - optional L56_in_pH / L56_out_pH may override L56_pH on the input/output
    external paths for topology ablation experiments;
  - top/bottom E1_B nodes are tied directly to E1TAP;
  - top/bottom MA_A nodes are tied directly to MATAP.

Accepted S4P logical port names are equivalent:
  E1_A == in1
  MA_B == out1
  E1_B == E1TAP
  MA_A == MATAP

External port order:
  1 in1, 2 in2, 3 out1, 4 out2, 5 E1TAP, 6 MATAP.
"""

from __future__ import annotations

from pathlib import Path

import skrf as rf
from skrf.circuit import Circuit
from skrf.media import DefinedGammaZ0

import TF_Cal_S6P_Predicting as old_tf


CFG = dict(old_tf.CFG)
CFG.update(
    {
        "out_prefix": "TF_Cal_S6P_Predicting_0504",
        "L56V_extra_pH": 0.0,
    }
)


def build_circuit(cfg: dict) -> rf.Network:
    freq = old_tf.make_frequency(cfg["f_start_ghz"], cfg["f_stop_ghz"], cfg["f_step_ghz"])
    z0 = cfg["z0"]
    ideal = DefinedGammaZ0(frequency=freq, z0=z0)

    port_in1 = Circuit.Port(freq, name="in1", z0=z0)
    port_in2 = Circuit.Port(freq, name="in2", z0=z0)
    port_out1 = Circuit.Port(freq, name="out1", z0=z0)
    port_out2 = Circuit.Port(freq, name="out2", z0=z0)
    port_e1tap = Circuit.Port(freq, name="E1TAP", z0=z0)
    port_matap = Circuit.Port(freq, name="MATAP", z0=z0)

    s4p_top = rf.Network(cfg["s4p_top"])
    s4p_top.name = "S4P_TOP"
    s4p_top = old_tf.align_network_to_freq(s4p_top, freq)

    s4p_bot = rf.Network(cfg["s4p_bot"])
    s4p_bot.name = "S4P_BOT"
    s4p_bot = old_tf.align_network_to_freq(s4p_bot, freq)

    top_ports = old_tf.infer_s4p_port_indices(s4p_top, cfg)
    bot_ports = old_tf.infer_s4p_port_indices(s4p_bot, cfg)

    l56_in_pH = cfg.get("L56_in_pH", cfg["L56_pH"])
    l56_out_pH = cfg.get("L56_out_pH", cfg["L56_pH"])
    l56_in_base = old_tf.ideal_series_inductor(ideal, float(l56_in_pH) * 1e-12, "L56_in_base")
    l56_out_base = old_tf.ideal_series_inductor(ideal, float(l56_out_pH) * 1e-12, "L56_out_base")
    l13_base = old_tf.ideal_series_inductor(ideal, cfg["L13_nH"] * 1e-9, "L13_base")
    l24_base = old_tf.ideal_series_inductor(ideal, cfg["L24_nH"] * 1e-9, "L24_base")

    L67 = old_tf.copy_named(l56_in_base, "L67")
    L66 = old_tf.copy_named(l56_in_base, "L66")
    L89 = old_tf.copy_named(l56_out_base, "L89")
    L88 = old_tf.copy_named(l56_out_base, "L88")
    L68 = old_tf.copy_named(l13_base, "L68")
    L73 = old_tf.copy_named(l13_base, "L73")
    L24_TOP_IN_E1 = old_tf.copy_named(l24_base, "L24_TOP_IN_E1")
    L24_TOP_OUT_MA = old_tf.copy_named(l24_base, "L24_TOP_OUT_MA")
    L24_BOT_IN_E1 = old_tf.copy_named(l24_base, "L24_BOT_IN_E1")
    L24_BOT_OUT_MA = old_tf.copy_named(l24_base, "L24_BOT_OUT_MA")

    cnx = [
        [(port_in1, 0), (L67, 0), (L68, 0)],
        [(port_in2, 0), (L66, 0), (L68, 1)],
        [(L67, 1), (s4p_top, top_ports["E1_A"]), (L24_TOP_IN_E1, 0)],
        [(L66, 1), (s4p_bot, bot_ports["E1_A"]), (L24_BOT_IN_E1, 0)],
        [(L89, 1), (port_out1, 0), (L73, 0)],
        [(L88, 1), (port_out2, 0), (L73, 1)],
        [(s4p_top, top_ports["MA_B"]), (L89, 0), (L24_TOP_OUT_MA, 0)],
        [(s4p_bot, bot_ports["MA_B"]), (L88, 0), (L24_BOT_OUT_MA, 0)],
        [
            (s4p_top, top_ports["E1_B"]),
            (s4p_bot, bot_ports["E1_B"]),
            (port_e1tap, 0),
            (L24_TOP_IN_E1, 1),
            (L24_BOT_IN_E1, 1),
        ],
        [
            (s4p_top, top_ports["MA_A"]),
            (s4p_bot, bot_ports["MA_A"]),
            (port_matap, 0),
            (L24_TOP_OUT_MA, 1),
            (L24_BOT_OUT_MA, 1),
        ],
    ]

    ntw = Circuit(cnx).network
    ntw.name = "TF_Cal_S6P_Predicting_0504"
    ntw.port_names = ["in1", "in2", "out1", "out2", "E1TAP", "MATAP"]
    return ntw


def build_tf_6port(cfg: dict) -> rf.Network:
    return build_circuit(cfg)


def write_s6p(ntw: rf.Network, cfg: dict) -> Path:
    out_dir = Path(cfg.get("out_dir", "."))
    out_dir.mkdir(parents=True, exist_ok=True)
    out_name = cfg.get("out_name") or cfg.get("out_prefix", "TF_Cal_S6P_Predicting_0504")
    out_prefix = out_dir / str(out_name)
    ntw.write_touchstone(str(out_prefix))
    return out_prefix.with_suffix(".s6p")


def main() -> None:
    ntw = build_tf_6port(CFG)
    print(ntw)
    write_s6p(ntw, CFG)


if __name__ == "__main__":
    main()
